[tool.black]
line-length = 119
target-version = ["py38"]

[tool.isort]
src_paths = ""
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 119
ensure_newline_before_comments = true
lines_after_imports = 2
known_first_party = "raiev"

[tool.nbqa.config]
isort = "pyproject.toml"
black = "pyproject.toml"
flake8 = "setup.cfg"
mypy = "setup.cfg"

[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1

[tool.nbqa.addopts]
pyupgrade = ["--py38-plus"]

[tool.nbqa.ignore_cells]
isort = "%sh,%pip,%conda"
black = "%sh,%pip,%conda"
flake8 = "%sh,%sh,%pip,%conda"
pyupgrade = "%sh,%pip,%conda"
mypy = "%sh,%pip,%conda"
